apiVersion: v1
kind: Service
metadata:
  name: {{ include "net-istio.fullname" . }}-webhook
  labels:
    {{- include "net-istio.labels" . | nindent 4 }}
    {{- include "net-istio.webhookSelectorLabels" . | nindent 4 }}
spec:
  type: {{ .Values.webhook.service.type }}
  selector:
    {{- include "net-istio.selectorLabels" . | nindent 4 }}
    {{- include "net-istio.webhookSelectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.webhook.service.ports | toYaml | nindent 2 }}
