{{- if .Values.configIstio.configMap.create -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  labels:
    {{- include "net-istio.labels" . | nindent 4 }}
data:
  {{- $example := pick .Values.configIstio.data "_example" -}}
  {{- $sanitized := omit .Values.configIstio.data "_example" -}}
  {{- toYaml $example | nindent 2 }}
  {{- tpl (toYaml $sanitized) . | nindent 2 }}
{{- end }}
