apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "net-istio.fullname" . }}-knative-serving-istio
  labels:
    serving.knative.dev/controller: "true"
  {{- include "net-istio.labels" . | nindent 4 }}
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - virtualservices
  - gateways
  - destinationrules
  verbs:
  - get
  - list
  - create
  - update
  - delete
  - patch
  - watch
