{{- if .Values.istio.ingressGateway.create -}}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Values.istio.ingressGateway.name }}
  labels:
  {{- include "net-istio.labels" . | nindent 4 }}
spec:
  {{- with .Values.istio.ingressGateway.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.istio.ingressGateway.servers }}
  servers:
  {{- toYaml . | nindent 2 }}
  {{- end }}
{{- end }}
