global:
  config:
    configLoggingName: config-logging
    configObservabilityName: config-observability
    metricsDomain: knative.dev/internal/serving

kubernetesClusterDomain: cluster.local

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # The name of the knative-serving controller service account to use for the deployments.
  # Defaults to `controller` if empty
  name: ""

controller:
  image:
    repository: gcr.io/knative-releases/knative.dev/net-istio/cmd/controller
    tag: ""
    digest: sha256:53b28cc099b7e2357513e9643c029b200eb6b8c7eb2279961c7e79b677a8a2b7
    pullPolicy: IfNotPresent

  extraEnv:
  - name: ENABLE_SECRET_INFORMER_FILTERING_BY_CERT_UID
    value: "false"

  podAnnotations: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: []

  resources:
    limits:
      cpu: 300m
      memory: 400Mi
    requests:
      cpu: 30m
      memory: 40Mi

webhook:
  image:
    repository: gcr.io/knative-releases/knative.dev/net-istio/cmd/webhook
    tag: ""
    digest: sha256:90083eb29e6ab29a352fbf606257ca397e4039acb12f7c08152dc1e409e5ce50
    pullPolicy: IfNotPresent

  extraEnv: []

  podAnnotations: {}

  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  resources:
    limits:
      cpu: 200m
      memory: 200Mi
    requests:
      cpu: 20m
      memory: 20Mi

  nodeSelector: {}

  tolerations: []

  affinity: {}

  topologySpreadConstraints: []

  service:
    type: ClusterIP
    ports:
    - name: http-metrics
      port: 9090
      targetPort: metrics
    - name: http-profiling
      port: 8008
      targetPort: profiling
    - name: https-webhook
      port: 443
      targetPort: https-webhook

configIstio:
  configMap:
    create: true
  data:
    _example: |-
      ################################
      #                              #
      #    EXAMPLE CONFIGURATION     #
      #                              #
      ################################
      # This block is not actually functional configuration,
      # but serves to illustrate the available configuration
      # options and document them in a way that is accessible
      # to users that `kubectl edit` this config map.
      #
      # These sample configuration options may be copied out of
      # this example block and unindented to be in the data block
      # to actually change the configuration.
      # A gateway and Istio service to serve external traffic.
      # The configuration format should be
      # `gateway.{{gateway_namespace}}.{{gateway_name}}: "{{ingress_name}}.{{ingress_namespace}}.svc.cluster.local"`.
      # The {{gateway_namespace}} is optional; when it is omitted, the system will search for
      # the gateway in the serving system namespace `knative-serving`
      gateway.knative-serving.knative-ingress-gateway: "istio-ingressgateway.istio-system.svc.cluster.local"
      # A cluster local gateway to allow pods outside of the mesh to access
      # Services and Routes not exposing through an ingress.  If the users
      # do have a service mesh setup, this isn't required and can be removed.
      #
      # An example use case is when users want to use Istio without any
      # sidecar injection (like Knative's istio-ci-no-mesh.yaml).  Since every pod
      # is outside of the service mesh in that case, a cluster-local  service
      # will need to be exposed to a cluster-local gateway to be accessible.
      # The configuration format should be `local-gateway.{{local_gateway_namespace}}.
      # {{local_gateway_name}}: "{{cluster_local_gateway_name}}.
      # {{cluster_local_gateway_namespace}}.svc.cluster.local"`. The
      # {{local_gateway_namespace}} is optional; when it is omitted, the system
      # will search for the local gateway in the serving system namespace
      # `knative-serving`
      local-gateway.knative-serving.knative-local-gateway: "knative-local-gateway.istio-system.svc.cluster.local"

istio:
  # the namespace where istio runs
  namespace: istio-system
  ingressGateway:
    create: true
    name: knative-ingress-gateway
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 80
        protocol: HTTP
  localGateway:
    create: true
    name: knative-local-gateway
    selector:
      istio: ingressgateway
    servers:
    - hosts:
      - '*'
      port:
        name: http
        number: 8081
        protocol: HTTP
    service:
      create: true
      type: ClusterIP
      ports:
      - name: http2
        port: 80
        targetPort: 8081
